# Generated by Django 3.2.8 on 2021-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=250)),
                ('address', models.TextField()),
                ('zip_code', models.CharField(max_length=8)),
            ],
        ),
    ]
