# Generated by Django 3.2.8 on 2021-12-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.EmailField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
