# Generated by Django 3.2.8 on 2021-12-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20211205_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('main', models.ImageField(upload_to='pics')),
                ('im1', models.ImageField(upload_to='pics')),
                ('im2', models.ImageField(upload_to='pics')),
                ('im3', models.ImageField(upload_to='pics')),
                ('im4', models.ImageField(upload_to='pics')),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
