# Generated by Django 3.2.8 on 2021-12-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='shoe', max_length=50),
        ),
    ]
