# Generated by Django 3.2.8 on 2021-12-15 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.user_details')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.products')),
            ],
        ),
    ]
