# Generated by Django 3.2.8 on 2021-12-16 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_user_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_products',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='user_products',
            name='quantity',
        ),
    ]
