# Generated by Django 3.2.8 on 2021-12-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20211216_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_products',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user_products',
            name='pro_id',
            field=models.CharField(max_length=100),
        ),
    ]
